### PR TITLE
State/outdated

### PR DESCRIPTION
**Pull request by DigitalKnight0**
This branch implements how the feature discussed on discord will look like in a very basic form 
Note: This is just to depict the working, the styling and functionality will be more complex and suited for the purpose

### CODE REVIEW

**Comment by DigitalKnight0** [comment]
The feature can be previewed at https://digitalknight0.github.io/zap-simulator/

**Comment by Mclilzee** [comment]
@DigitalKnight0 we did some improvements on the design, make sure to pull the latest version.

**Comment by DigitalKnight0** [comment]
@Mclilzee is this still a thing?

**Comment by DigitalKnight0** [comment]
^ This particular feature to be specific

**Comment by Mclilzee** [comment]
Ofc, and the core members loved it.

**Comment by DigitalKnight0** [comment]
Oh. Never heard back in the channel so assumed it was rejected

**Comment by Mclilzee** [comment]
@DigitalKnight0 btw, it was said this is our project. so we can do whatever we want with it, and as long as it reflects the matrix correctly, then everything is fine.

**Pull request closed without merging**
