### PR TITLE
adjust brightness of buttons on hover

### PR DESCRIPTION
**Pull request by JuanDCeballos**
Instead of having opacity of 0.8 on hover elements, I added a brightness of 115% when hovering a button.

Let me know what do you think about the changes.

### CODE REVIEW

**Comment by DigitalKnight0** [comment]
@JuanDCeballos thank you for doing this. There was some restructuring done previously with the project's history, so can you remove the extra commits?

**Comment by JuanDCeballos** [comment]
Honestly, I don't know how to do that.
Do you have a good resource I can follow to achieve that, if so, I'll be more than glad to remove the extra commits.

**Comment by DigitalKnight0** [comment]
@JuanDCeballos You might have to make a reset on your fork back to the last commit on upstream/main. You can stash any local changes to re-add them on the new commit. That said, let me know if you would do it or i can take this one!

**Comment by JuanDCeballos** [comment]
@DigitalKnight0 you can work on this one.

I don't want to ruin anything or maybe enter a bug, anyways thanks for having me in account.

**Pull request closed without merging**
